[language-server.verible-verilog-ls]
command = "verible-verilog-ls"
[language-server.svls]
command = "svls"
[language-server.veridian]
command = "veridian"

# C/C++
[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args  = ["-style=file"] }
indent = { tab-width = 2, unit = "  " }
[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format", args  = ["-style=file"] }
indent = { tab-width = 2, unit = "  " }
# Rust
[[language]]
name = "rust"
auto-format = true
# Verilog and SystemVerilog
[[language]]
name = "verilog"
scope = "source.verilog"
auto-format = true
language-servers = [ "veridian" ]
formatter = { command = "verible-verilog-format", args = ["--column_limit=120", "--indentation_spaces=4", "-"] }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "verilog"
source = { git = "https://github.com/tree-sitter/tree-sitter-verilog.git", rev = "075ebfc84543675f12e79a955f79d717772dcef3" }
